spring:
  application:
    name: eureka-server
server:
  port: 8881
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8881/eureka/
    fetch-registry: false
    register-with-eureka: false
