spring:
  application:
    name: oauth-server-dev

  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://121.42.238.128/oauth2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      username: hotel
      password: internet

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  redis:
#    host: 172.16.10.43
#    database: 1

server:
  port: 8890
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761//eureka/
security:
  oauth2:
    resource:
      id: oauth-server-dev
#使用spring-security的拦截器
#security:
#  oauth2:
#    resource:
#      filter-order: 3


#logging.level.org.springframework.security: DEBUG
